services:
  simulador_container:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: simulador_container
    network_mode: "host"
    ipc: host
    devices:
    - /dev/dri:/dev/dri
    group_add:
      - "44"
      - "992"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
    volumes:
      - ../:/home/humble_user/sim_ws/src
    stdin_open: true
    tty: true
